name: mtg_deck_builder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  flutter_svg_provider: ^1.0.7
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  mobx: ^2.3.3+2
  scryfall_api: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
